### ISSUE TITLE
v2 版本跑不起来

### ISSUE THREAD

**Issue by Shimada666** [kakajun/vue3-sketch-ruler#10]
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/33391300/183245721-d46872ae-d4bf-475f-995c-8ff9b874bfce.png">

**Comment by kakajun** [comment]
看到这个错误我开始以为版本升级了, 其实是你没有切版本,我已经把实例直接指定到v2, 你切不切都能跑起来
import SketchRule from '../../../lib/v2/index.es'
