### ISSUE TITLE
自定义图标后点击图标提示 runtime-core.esm-bundler.js:38 [Vue warn]: Component emitted event "handleCornerClick" but it is neither declared in the emits option nor as an "onHandleCornerClick" prop.

### ISSUE THREAD

**Issue by zhangchenna** [kakajun/vue3-sketch-ruler#12]
自定义图标后点击图标提示 runtime-core.esm-bundler.js:38 [Vue warn]: Component emitted event "handleCornerClick" but it is neither declared in the emits option nor as an "onHandleCornerClick" prop.

**Comment by zhangchenna** [comment]
这种写法不规范，建议修改下

**Comment by kakajun** [comment]
1.3.7 修复了 onHandleCornerClick
