### ISSUE TITLE
如何打包兼容ui库

### ISSUE THREAD

**Issue by SilverComet7** [kakajun/vue3-sketch-ruler#13]
大佬，如果我的组件引用了第三方的ui库，比如Element-ui，其也有2个版本，如何使打包出来的文件同样兼容vue2和vue3呢？

**Comment by kakajun** [comment]
> 大佬，如果我的组件引用了第三方的ui库，比如Element-ui，其也有2个版本，如何使打包出来的文件同样兼容vue2和vue3呢？

不行的, demi打出来的, 其插件都能适配, 那么我直接打包了element ui 到vue3里面用就好了呀, 那为什么还要花那么多时间重新搞个element-plus呢, 注意我这个插件里面是主体代码用vue3的形式写的, 然后向下兼容的, 并不能向上兼容, 也就是插件有element-ui等vue2时的插件, 并不能在里面有

**Comment by SilverComet7** [comment]
我想通过vue3+Element-plus构建出能在vue2项目或vue3项目中可使用的通用组件，这种方式可行吗？
[这是我的仓库demo](https://github.com/SilverComet7/Component-library/blob/master/packages/VueComponent/README.md)
现在只能在vue3一端使用，thanks

**Comment by SilverComet7** [comment]
> > 大佬，如果我的组件引用了第三方的ui库，比如Element-ui，其也有2个版本，如何使打包出来的文件同样兼容vue2和vue3呢？
> 
> 不行的, demi打出来的, 其插件都能适配, 那么我直接打包了element ui 到vue3里面用就好了呀, 那为什么还要花那么多时间重新搞个element-plus呢, 注意我这个插件里面是主体代码用vue3的形式写的, 然后向下兼容的, 并不能向上兼容, 也就是插件有element-ui等vue2时的插件, 并不能在里面有

我想通过vue3+Element-plus构建出能在vue2项目或vue3项目中可使用的通用组件，这种方式可行吗？
[这是我的仓库demo](https://github.com/SilverComet7/Component-library/blob/master/packages/VueComponent/README.md)
现在只能在vue3一端使用，thanks
