### ISSUE TITLE
使用报错：Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by liangt0425** [kakajun/vue3-sketch-ruler#14]
vue版本：3.0.2
复现demo：[https://github.com/tong104218/rule-demo](https://github.com/tong104218/rule-demo)

**Comment by kakajun** [comment]
> vue版本：3.0.2 复现demo：https://github.com/tong104218/rule-demo

用3.2.20 是可以的， 我当时开发是用的这个版本， 可能写法里面，低的版本不支持吧
