### ISSUE TITLE
部署到线上后样式丢失

### ISSUE THREAD

**Issue by zhuanglinxin** [kakajun/vue3-sketch-ruler#15]
您好，请问一下vue3打包部署到线上后样式丢失，在本地开发是没问题的，怎么解决

**Comment by kakajun** [comment]
> 您好，请问一下vue3打包部署到线上后样式丢失，在本地开发是没问题的，怎么解决

![image](https://user-images.githubusercontent.com/38216933/203936499-73a2f643-8d14-4254-b3ee-0a9968842118.png)
你看我gh-pages 其实就是线上打包部署，为啥没有样式丢失？
