### ISSUE TITLE
参考线刻度好像不准确

### ISSUE THREAD

**Issue by yynyynyyn** [kakajun/vue3-sketch-ruler#17]
高度的参考线
![image](https://user-images.githubusercontent.com/50070237/205558059-cd57cdd1-0f73-42cb-9029-5626c7843213.png)

**Comment by kakajun** [comment]
> 高度的参考线 ![image](https://user-images.githubusercontent.com/50070237/205558059-cd57cdd1-0f73-42cb-9029-5626c7843213.png)

这个是因为给的宽高不准吧, 可以看下参考例子 
https://kakajun.github.io/vue3-sketch-ruler/1x/
