### ISSUE TITLE
vue3.x中 删除标尺线 不会立即删除

### ISSUE THREAD

**Issue by crismcn** [kakajun/vue3-sketch-ruler#18]

**Comment by kakajun** [comment]
可以看下demo里面是可以的哦
https://kakajun.github.io/vue3-sketch-ruler/1x/

**Comment by kakajun** [comment]
> _No description provided._

可以看下demo里面是可以的哦
https://kakajun.github.io/vue3-sketch-ruler/1x/

**Comment by gamolins** [comment]
您好，这个问题您解决了嘛？我这边是点击不会删除，点完x后，需要把鼠标放到标尺上才会立刻删除，您怎么解决无法立即删除问题的？

**Comment by gamolins** [comment]
> 您好，这个问题您解决了嘛？我这边是点击不会删除，点完x后，需要把鼠标放到标尺上才会立刻删除，您怎么解决无法立即删除问题的？

没有给lines加默认值，加完默认值就会立即删除

**Comment by wuyingjie-ways** [comment]
> 
lines: {
    h: [],
    v: []
  },

**Comment by kakajun** [comment]
1X 已不再维护
