### ISSUE TITLE
vue3.x，当去掉滚动条后，刻度显示不准确

### ISSUE THREAD

**Issue by Brid9e** [kakajun/vue3-sketch-ruler#19]
![image](https://user-images.githubusercontent.com/85558909/215368923-fda6fc98-bed1-43d5-baf8-875663442d34.png)

**Comment by kakajun** [comment]
css 也要配合, 我demo里面有写的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kakajun/vue3-sketch-ruler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 上午9:24
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[kakajun/vue3-sketch-ruler] vue3.x，当去掉滚动条后，刻度显示不准确 (Issue #19)

**Comment by llx007139** [comment]
![1716349351918](https://github.com/kakajun/vue3-sketch-ruler/assets/111190698/5476cd9c-a53d-4e7a-ac0c-3de2ec9f74f0)

刻度显示不全，已经确认正确引入插件css了，也排查过想的适配js的原因。使用的是vite+vue3

**Comment by kakajun** [comment]
1x已不再维护
