### ISSUE TITLE
1.3.9 + lib no files

### ISSUE THREAD

**Issue by xstxhjh** [kakajun/vue3-sketch-ruler#24]
<img width="795" alt="image" src="https://github.com/kakajun/vue3-sketch-ruler/assets/33480698/ee890a00-b7d1-433b-81b2-0123d1357b65">
<img width="795" alt="image" src="https://github.com/kakajun/vue3-sketch-ruler/assets/33480698/f38c5d1b-0f7e-47be-aee7-c1f8e11307f1">

Failure to import {SketchRule} from'vue3-sketch-ruler';

**Comment by kakajun** [comment]
packges里面写反了, 这里重新发包  "vue3-sketch-ruler": "1.3.14"
