### ISSUE TITLE
mac2k浏览器下，标尺不对，外接屏显示正常

### ISSUE THREAD

**Issue by QianSu** [kakajun/vue3-sketch-ruler#26]
![image](https://github.com/kakajun/vue3-sketch-ruler/assets/21114827/b4752da1-7123-4450-a7bb-3637367d8a26)
<img width="1091" alt="image" src="https://github.com/kakajun/vue3-sketch-ruler/assets/21114827/0a38def5-2043-46b2-b0d9-a80c28d0be6b">

**Comment by rkrv01** [comment]
> 屏幕缩放比例导致的，控件设置ratio="1"可以解决

这个设置具体在哪，我也遇到了同样的问题

**Comment by kakajun** [comment]
1x已不再维护

**Comment by Rile14929** [comment]
> > 屏幕缩放比例导致的，控件设置ratio="1"可以解决
> 
> 这个设置具体在哪，我也遇到了同样的问题

我也遇到这个问题了，在这设置一下就好了
![image](https://github.com/user-attachments/assets/239301a8-a408-4a6a-b8c7-85690538a4d1)
