### ISSUE TITLE
显示器缩放150%出现的标尺刻度异常问题

### ISSUE THREAD

**Issue by shuxinyun** [kakajun/vue3-sketch-ruler#29]
显示器缩放100%都是非常正常。
当显示器缩放为150%的时候，刻度尺如下：

<img width="203" alt="1" src="https://github.com/kakajun/vue3-sketch-ruler/assets/29122991/79181194-e2ba-4e3d-b0da-462363132c94">

当设置ratio=1的时候显示如下：
<img width="122" alt="1719633567385" src="https://github.com/kakajun/vue3-sketch-ruler/assets/29122991/160bfc21-1a85-4de6-99cd-b8d9332673c4">

初步判断是这里如下地方计算有误(没有与ratio相关所致)：
<img width="960" alt="1719633658086" src="https://github.com/kakajun/vue3-sketch-ruler/assets/29122991/63f36aea-34c8-46af-8b90-7946461bb626">

还请帮忙处理一下

**Comment by Rile14929** [comment]
1X版本下，设置一下这个属性

https://github.com/kakajun/vue3-sketch-ruler/issues/26#issuecomment-2244123637
