### ISSUE TITLE
期望拖拽线的区域不限于小范围

### ISSUE THREAD

**Issue by xmflswood** [kakajun/vue3-sketch-ruler#3]
目前拖拽线的操作区域只限于标尺附近，期望整根线都可以拖拽

**Comment by kakajun** [comment]
能画个示意图么？这样子方便我更加理解这个需求



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月7日(周五) 下午4:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [kakajun/vue3-sketch-ruler] 期望拖拽线的区域不限于小范围 (Issue #3)




 
目前拖拽线的操作区域只限于标尺附近，期望整根线都可以拖拽
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xmflswood** [comment]
![impicture_20220111_193739](https://user-images.githubusercontent.com/13427833/148935980-35980b12-e2dc-40d6-a3bc-c55dc27f61ad.png)
@kakajun 
目前可以拖拽的区域受限于红框部分，期望整条线都可以

**Comment by kakajun** [comment]
也就是希望线条撑满全屏是吧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月11日(周二) 晚上7:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kakajun/vue3-sketch-ruler] 期望拖拽线的区域不限于小范围 (Issue #3)




 

 @kakajun
 目前可以拖拽的区域受限于红框部分，期望整条线都可以
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xmflswood** [comment]
@kakajun 
希望在绿色的区域也可以拖拽这条线

**Comment by kakajun** [comment]
了解了，这个我试试，好了会通知你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月12日(周三) 中午1:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kakajun/vue3-sketch-ruler] 期望拖拽线的区域不限于小范围 (Issue #3)




 
@kakajun
 希望在绿色的区域也可以拖拽这条线
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kakajun** [comment]
已经修改好了 @xmflswood
