### ISSUE TITLE
大佬,小弟提几个需求,看能否帮下忙

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#31]
首先感谢大佬能写出如此优秀的插件,大赞.
试用了一天,结合我们项目目前的需求,提出几个小需求看能否帮忙加一下

1.把startX,startY放出来,可以配置
2.把睁眼闭眼那个图标是否显示也放出来,不太想显示那个图标
3.看到您把小刻度去掉了,希望您可以增加一个是否显示小刻度,如果能顺便把小刻度步长暴露出来可以配置就更完美了
4.如果能把移动画布及放大监听的方法放出来就更完美了,可能我们的产品经理想法不一样,需要按到的按键也不一样

这几个需求如果实现了对我来说就太好了,对您来说这个插件适用性更广,谢谢您

**Comment by kakajun** [comment]
谢谢您提的几点需求
首先,您提的2,第4条, 我会在后面加入
其他两条就目前而言, 我觉得没必要, 我说下原因, 这边2X版本, 主打的就是搞一个市场最受欢迎的这个平台, 否则没有革新的话, 那么我也没必要搞个2X, 大家都用1X就行了,
1.  2X主打就是一个少配置(1X要调配的东西很多), 开箱即用, 比如缩放, 平移尺子, 居中, 我这个插件里面就内置
2.  小刻度没有必要再显示了, 我参考了, 比如 [搞定](https://www.gaoding.com/), [即刻设计](https://js.design/) 都没有小刻度, 而且也感觉有密集恐惧, 用拖拽时标签显示刻度已经代替了小刻度.
当然, 如果您坚持需要小刻度, 也可以pr给我

**Comment by bert1020** [comment]
谢谢您
