### ISSUE TITLE
参考demo显示有问题，不在正中心

### ISSUE THREAD

**Issue by RowgerGo** [kakajun/vue3-sketch-ruler#37]
github
![正中心](https://github.com/user-attachments/assets/1a049482-8cd1-42a4-8a9c-46f2aad35e18)
参考https://kakajun.github.io/vue3-sketch-ruler/这个demo
const rectWidth = ref(1600)
const rectHeight = ref(900)

const canvasWidth = ref(1200)
const canvasHeight = ref(600)
我把画布大小设置为1200*600，但是它最后位置不在正中间

**Comment by RowgerGo** [comment]
![正常页面](https://github.com/user-attachments/assets/a04f6421-adcd-4751-9b58-27e372898efa)
![异常页面](https://github.com/user-attachments/assets/204d6a6b-21db-432d-806d-46f54c2cd71e)
我期望得到的效果是图1那样的，但是实际效果是图2.图片在画布中没有居中，或者说y轴的起始点太靠右了

**Comment by kakajun** [comment]
已修复
