### ISSUE TITLE
bug 放大缩小有bug

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#39]
先放到最大 再缩小 就会死循环打印下面这个,导致页面卡死

const cpuScale = computed(() => {
  const num = Number(state.scale)
  console.log(num)
  return num.toFixed(2)
})

**Comment by bert1020** [comment]
还有个bug 放大缩小几次之后 刻度尺跟实际就对应不上了
拖拽开始的一瞬间又会对的上
![image](https://github.com/user-attachments/assets/b1a4dd97-083e-46a9-ab27-cc3a39385390)

**Comment by bert1020** [comment]
还有bug ,初始化设置缩放值1 , onMounted之后我会获取layout的宽高 和 编辑页面设置的宽高算出来一个缩放值 ,比如这个值算出来的是0.7 ,然后通过一下代码设置缩放
` nextTick(()=>{
    state.scale = computedZoom(rectWidth.value, rectHeight.value);
    if (sketchruleRef.value) {
      const panzoomInstance = sketchruleRef.value.panzoomInstance
      panzoomInstance.zoom(state.scale)
    }
    console.log('缩放xxx', state.scale)
  })`

这样子页面显示正常 ,但是当我还原的时候缩放值又回到1了.

当我在执行一下代码时
` if (sketchruleRef.value) {
      sketchruleRef.value.reset()
    }
    state.scale = computedZoom(rectWidth.value, rectHeight.value);
    if (sketchruleRef.value) {
      const panzoomInstance = sketchruleRef.value.panzoomInstance
      panzoomInstance.zoom(state.scale)
    }
    console.log('缩放xxx', state.scale)`
页面虽然正常显示了,但是state.scale 又变成1了

**Comment by bert1020** [comment]
应该是有个值来设置加载后的缩放值,你拿第一次设置的缩放值作为加载后的缩放值了,同时这个值也作为了实时的缩放值,应该两个值区分开来 当我调用sketchruleRef.value.reset()方法时 直接用加载后的缩放值重置就好了

**Comment by kakajun** [comment]
> 应该是有个值来设置加载后的缩放值,你拿第一次设置的缩放值作为加载后的缩放值了,同时这个值也作为了实时的缩放值,应该两个值区分开来 当我调用sketchruleRef.value.reset()方法时 直接用加载后的缩放值重置就好了

再看看呢? 我又发了个新版
