### ISSUE TITLE
眼睛icon太模糊了 希望可以加个插槽自定义或者可以替换图片

### ISSUE THREAD

**Issue by zhangchenna** [kakajun/vue3-sketch-ruler#4]

**Comment by kakajun** [comment]
不模糊啊, 这编辑界面不是只在电脑上面操作展示么? 又不会在大分辨率的屏幕上显示是吧

**Comment by zhangchenna** [comment]
我在5K的imac上看比较模糊，另外他的zindex比较低如果拖拽组件 还是 旁边的坐标都会在他的层级之上

**Comment by kakajun** [comment]
> 

已经修改
![image](https://user-images.githubusercontent.com/38216933/151274607-87916e83-553c-401e-9c2a-59a64eaef05f.png)

https://www.npmjs.com/package/vue3-sketch-ruler/v/1.3.2
