### ISSUE TITLE
bug  上下间隔有问题

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#40]
缩放值越小,小于0.5是最明显的  
上下不对称
![image](https://github.com/user-attachments/assets/e89c92d0-54ff-44c9-b8fe-f2d9bcce76ec)

**Comment by bert1020** [comment]
弄得是一个3000成2000的分辨率

**Comment by bert1020** [comment]
![image](https://github.com/user-attachments/assets/4ba930d8-c7c3-440c-83f0-bcbe67eb81ce)
当我把:paddingRatio="0"设置为0的时候  上面这块区域哪来的

**Comment by bert1020** [comment]
您的样例程序  
设置paddingRatio="0"
const rectWidth = ref(1852)
const rectHeight = ref(843)
const canvasWidth = ref(3000)
const canvasHeight = ref(2000)

就会很明显

**Comment by bert1020** [comment]
我理解的Y轴偏移量应该 (props.canvasHeight * scale - props.canvasHeight) / 2  但为啥效果不理想 不得其解

**Comment by kakajun** [comment]
> 我理解的Y轴偏移量应该 (props.canvasHeight * scale - props.canvasHeight) / 2 但为啥效果不理想 不得其解

说实话, 我早就发现这个问题了, 居中算法你看提交记录我都换了好几版了, 我自己写demo, 一点问题都没, 我估计还是panzoom插件有问题, 有时间考虑原生改造一下
![image](https://github.com/user-attachments/assets/790cc09c-c9a5-4478-82df-84f8015e661e)

**Comment by bert1020** [comment]
我把缩放起点 设置成了左上角  
`
const getPanOptions = (scale: number) => {
  return {
    noBind: true,
    startScale: scale,
    cursor: 'default',
    startX: zoomStartX.value,
    startY: zoomStartY.value,
    smoothScroll: true,
    origin: '0 0',
    ...props.panzoomOption
  }
}`
然后居中算法改成这样
`  zoomStartX.value = (rectWidth.value - props.canvasWidth * scale) / 2 / scale
  zoomStartY.value = (rectHeight.value - props.canvasHeight * scale) / 2 / scale`

正确显示了,但是不是x轴标尺不显示 就是Y轴标尺不显示 . 剩下的缩放都是以左上角缩放了 也不行
我是这样想的 
第一次初始化这样设置,后面还要在哪里改成以中心点缩放 ,这个库没研究明白你看看行不行

**Comment by bert1020** [comment]
`  zoomStartX.value =
    (props.canvasWidth * scale) / 2 -
    props.canvasWidth / 2 +
    (rectWidth.value - props.canvasWidth * scale) / 2
  zoomStartY.value =
    ((props.canvasHeight * scale) / 2 - props.canvasHeight / 2) / scale +
    (props.canvasHeight * scale - rectHeight.value) / 2`

搞定咯,不用改变缩放起点 ,唯一遗憾的不知道 为啥Y轴需要除缩放,X轴不需要

**Comment by kakajun** [comment]
![image](https://github.com/user-attachments/assets/7259b246-2b4c-453d-8759-2e37837f1552)
const rectWidth = ref(1470)
const rectHeight = ref(872)

const canvasWidth = ref(530)
const canvasHeight = ref(250)
如果是这个比例, 就成了这样子, 我试了很多大小比例, 基本是X方向能居中, Y轴方法不行     
我有个短期想法就是从外头传一个修正值到里面, 返回不同尺寸的比例修正, 按经验去传, 怎么样?

**Comment by bert1020** [comment]
这次可以了,scale 大于1跟小于1 缩放的方式不一样 往大了缩放,中心点会一点一点的往左跑  ,
` if (scale <= 1) {
    zoomStartY.value =
      ((props.canvasHeight * scale) / 2 - props.canvasHeight / 2) / scale +
      (props.canvasHeight * scale - rectHeight.value) / 2
  } else {
    zoomStartY.value =
      (props.canvasHeight * scale - props.canvasHeight) / 2 / scale +
      (rectHeight.value - props.canvasHeight * scale) / scale / 2
  }`

**Comment by bert1020** [comment]
![image](https://github.com/user-attachments/assets/dc82a1ac-cf4f-43dd-a07e-263113d96cdd)
大了往小了缩 中心点不会变 ,小的往大的缩会像上图一样往左跑.

**Comment by kakajun** [comment]
![image](https://github.com/user-attachments/assets/c816b46b-a4cb-467e-afa8-42c58e52d88d)
const canvasWidth = ref(1920)
const canvasHeight = ref(1080)  scale 小于1 还是不得行, 大于1的用你的算法, 挺ok

**Comment by bert1020** [comment]
`  if (scale < 1) {
    zoomStartY.value =
      ((props.canvasHeight * scale) / 2 - props.canvasHeight / 2) / scale -
      (props.canvasHeight * scale - rectHeight.value) / 2
  } else if (scale > 1) {
    zoomStartY.value =
      (props.canvasHeight * scale - props.canvasHeight) / 2 / scale +
      (rectHeight.value - props.canvasHeight * scale) / scale / 2
  } else {
    zoomStartY.value = 0
  }`
可以了 你再试试 ,大于一 小于1我试了几个分辨率没事 等于1的时候标尺不显示了

**Comment by bert1020** [comment]
`if (scale < 1) {
    zoomStartY.value =
      ((props.canvasHeight * scale) / 2 - props.canvasHeight / 2) / scale -
      (props.canvasHeight * scale - rectHeight.value) / scale / 2
  } else if (scale > 1) {
    zoomStartY.value =
      (props.canvasHeight * scale - props.canvasHeight) / 2 / scale +
      (rectHeight.value - props.canvasHeight * scale) / scale / 2
  } else {
    zoomStartY.value = 0
  }
`
又改了一版  我测过几个分辨率 都ok的

**Comment by kakajun** [comment]
优秀,采纳了
