### ISSUE TITLE
空格和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况

### ISSUE THREAD

**Issue by maddenBoy** [kakajun/vue3-sketch-ruler#42]
键盘空格键和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况

https://github.com/user-attachments/assets/5fd72ef9-3dbe-435e-a91c-ff1f89f5bf75

**Comment by kakajun** [comment]
> 键盘空格键和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况
> 
>  bandicam.2024-08-01.14-50-23-351.mp4
我这边功能就是按住空格+ 鼠标点击就能拖拽画布啊

**Comment by maddenBoy** [comment]
> > 键盘空格键和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况
> > bandicam.2024-08-01.14-50-23-351.mp4
> > 我这边功能就是按住空格+ 鼠标点击就能拖拽画布啊

空格和鼠标同时快速多次点击进行拖拽后，会出现**只需按住空格键**即可拖拽画布的情况（就是说会出现只需按住空格+**移动**鼠标就可以拖拽画布的情况）

**Comment by kakajun** [comment]
> > > 键盘空格键和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况
> > > bandicam.2024-08-01.14-50-23-351.mp4
> > > 我这边功能就是按住空格+ 鼠标点击就能拖拽画布啊
> 
> 空格和鼠标同时快速多次点击进行拖拽后，会出现**只需按住空格键**即可拖拽画布的情况（就是说会出现只需按住空格+**移动**鼠标就可以拖拽画布的情况）

只按空格,不按鼠标能拖拽?

**Comment by maddenBoy** [comment]
shid

> > > > 键盘空格键和鼠标同时快速多次点击进行拖拽后，会出现只需按住空格键即可拖拽画布的情况
> > > > bandicam.2024-08-01.14-50-23-351.mp4
> > > > 我这边功能就是按住空格+ 鼠标点击就能拖拽画布啊
> > 
> > 
> > 空格和鼠标同时快速多次点击进行拖拽后，会出现**只需按住空格键**即可拖拽画布的情况（就是说会出现只需按住空格+**移动**鼠标就可以拖拽画布的情况）
> 
> 只按空格,不按鼠标能拖拽?

是的，目前发现鼠标和空格键同时多次点击的操作会出现这种情况

**Comment by maddenBoy** [comment]
这个视频huo或许会更清楚一点，鼠标点击时鼠标那里是有红圈显示的，左下角是键盘按键映射


https://github.com/user-attachments/assets/91eea87c-986c-492f-9b1e-4be8ea5fd5bd

**Comment by kakajun** [comment]
已修复

**Comment by maddenBoy** [comment]
> 已修复

demo中有更新修复好的版本吗，怎么看着好像没修复😂
