### ISSUE TITLE
阴影有问题

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#43]
当dpi大于1时  阴影就有问题了

**Comment by kakajun** [comment]
> 当dpi大于1时 阴影就有问题了

截图呢? 或者你也可以修复一下, 给到我一个pr

**Comment by bert1020** [comment]
![image](https://github.com/user-attachments/assets/cc0d93d0-35ac-428f-bbcd-5c682bdbde13)
我刚做前端几个月.....一个小菜鸡  原生canvas不太熟  我看你代码里面标尺那里有处理dpi

**Comment by bert1020** [comment]
const shadowX = ((selectStart - start) * scale) / window.devicePixelRatio // 阴影起点坐标
    const shadowWidth = (selectLength * scale) / window.devicePixelRatio // 阴影宽度
除一下正常了

**Comment by bert1020** [comment]
const shadowX = ((selectStart - start) * scale) / window.devicePixelRatio // 阴影起点坐标
    const shadowWidth = (selectLength * scale) / window.devicePixelRatio // 阴影宽度
除一下正常了

**Comment by kakajun** [comment]
采纳
