### ISSUE TITLE
刻度尺和标线不准确的问题

### ISSUE THREAD

**Issue by Design-duke** [kakajun/vue3-sketch-ruler#44]
遇到了一个问题，刻度尺和标线没有对齐。越往后误差越大，能告诉我下是哪里的问题或者bug吗
![image](https://github.com/user-attachments/assets/549196bc-6b27-4207-bfea-127df5099b88)

**Comment by kakajun** [comment]
> 遇到了一个问题，刻度尺和标线没有对齐。越往后误差越大，能告诉我下是哪里的问题或者bug吗 ![image](https://private-user-images.githubusercontent.com/89451137/355377244-549196bc-6b27-4207-bfea-127df5099b88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzY4NjEsIm5iZiI6MTcyMjkzNjU2MSwicGF0aCI6Ii84OTQ1MTEzNy8zNTUzNzcyNDQtNTQ5MTk2YmMtNmIyNy00MjA3LWJmZWEtMTI3ZGY1MDk5Yjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MjkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNGY0NDk1ZGFjY2RmYzA1YzJlYmExZjMwMTA2ZjA1OGI2Mzc4OGU2NzQyNTU1MDRmNDBiZTgwOTRiYmNiNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N8-c-LwJwWk051AtwhkyLoKKdpgTDJQNQvuc7fxLd9s)

能提供你的参数么, hover数值对么  
![image](https://github.com/user-attachments/assets/7969b13b-8a22-4abe-ac43-734387a9eb69)

**Comment by Design-duke** [comment]
"vue3-sketch-ruler": "^1.3.15"




用的1.3.15版本，是使用d3进行缩放的，hover数值指的是？







在 2024-08-06 17:41:09，"kakajun" ***@***.***> 写道：

遇到了一个问题，刻度尺和标线没有对齐。越往后误差越大，能告诉我下是哪里的问题或者bug吗

能提供你的参数么, hover数值对么
image.png (view on web)

**Comment by Design-duke** [comment]
大概就是缩放scale的范围设置在了0.01-40的区间，然后就有误差了，或者比例尺数值太大的问题？







在 2024-08-06 17:41:09，"kakajun" ***@***.***> 写道：

遇到了一个问题，刻度尺和标线没有对齐。越往后误差越大，能告诉我下是哪里的问题或者bug吗

能提供你的参数么, hover数值对么
image.png (view on web)

**Comment by kakajun** [comment]
1X 的问题我不会再修改了, 建议升级到2X吧
