### ISSUE TITLE
鼠标滚轮是不是被拦截了

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#45]
![image](https://github.com/user-attachments/assets/570c472f-5a68-46c7-a248-8de4e1887fb4)
我用中间滚轮按下 移动画布,  只有偶尔先用空格让他生效才能移动,我确定e.button ===1 是成立的

**Comment by kakajun** [comment]
> ![image](https://private-user-images.githubusercontent.com/46582197/356954116-570c472f-5a68-46c7-a248-8de4e1887fb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MDc2NjcsIm5iZiI6MTcyMzUwNzM2NywicGF0aCI6Ii80NjU4MjE5Ny8zNTY5NTQxMTYtNTcwYzQ3MmYtNWE2OC00NmM3LWEyNDgtOGRlNGUxODg3ZmI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAwMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjMwMDUzM2YzYTAxMWNlNGNiZGNjNTA4ODI4Y2ZhMWZlZDUyOWJkZjA5YjI1ZTliODI1MjIzMDllMTRmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C7vG_13tokrPQCjqPvdXL8uAN31zsvCr8tz93SFxMhg) 我用中间滚轮按下 移动画布, 只有偶尔先用空格让他生效才能移动,我确定e.button ===1 是成立的

pazoom 插件默认就是鼠标按下,开始移动, 
![image](https://github.com/user-attachments/assets/a694bf73-f88c-4c21-906b-2d2a4c0955f3)
但它也提供了其他方法, 我写了个自定义按键(暂时没通, 有时间完善)

**Comment by bert1020** [comment]
默认就是鼠标中间按键按下开始移动? 你的例子不行

**Comment by kakajun** [comment]
> 默认就是鼠标中间按键按下开始移动? 你的例子不行

经查看源码比对, 不能用mousedown,要使用pointerdown, 否则会出现缩放bug, 因为panzoom内部对pointerId有判断,而mousedown里面并没有pointerId  
![image](https://github.com/user-attachments/assets/cc245e23-f112-48ec-b9d2-b4e1bbecbb5a)

**Comment by bert1020** [comment]
nice极了
