### ISSUE TITLE
辅助线小问题

### ISSUE THREAD

**Issue by bert1020** [kakajun/vue3-sketch-ruler#47]
拖动辅助线时 卡尺上面老是一闪而过数字,那个应该隐藏掉

把辅助线的mousedown,mmouseup事件通知出来吧,因为我鼠标按下移动有个框选功能,我想鼠标放在辅助线上面就不让框选了.
不然就这样了,移动辅助线我框选也出来了 
![image](https://github.com/user-attachments/assets/ec34e3b1-e984-48f1-be33-9ea2c7c7f12e)

**Comment by kakajun** [comment]
已重新发布2.0.10 版本, 另外关于框选功能触发原因是层级没有处理好, 建议把尺规层级设置高一些, 如果还有问题, 参考 [goVIew](https://gitee.com/majun2232/go-view)  这是2X应用
