### ISSUE TITLE
是否可以整个操作面板都可以按住空格拖动呢？

### ISSUE THREAD

**Issue by CandyACE** [kakajun/vue3-sketch-ruler#52]
![image](https://github.com/user-attachments/assets/ac09335c-4247-42ed-9898-22d8d055b94b)

**Comment by kakajun** [comment]
目前这种绝对定位的方式暂时不能解决这个需求, 但也不是没有办法, 换一个定位, 用margin做, 就像pazoom官网里面的demo一样, 当时我之所以采用绝对定位是为了方便计算尺子的距离, 你说的这个需求, 估计要等3X, 我有时间了, 再全部重写一遍

**Comment by CandyACE** [comment]
已经在最新版本上解决
