### ISSUE TITLE
调色板响应性丢失

### ISSUE THREAD

**Issue by xiaojunjie-chn** [kakajun/vue3-sketch-ruler#55]
版本：2.2.2
切换亮色暗色主题，标尺的阴影颜色不跟随变化
```typescript
const rulerPalette = computed(() => {
  return settingsStore.isDark
    ? {
        bgColor: 'transparent',
        hoverBg: '#fff',
        hoverColor: '#000',
        longfgColor: '#BABBBC', // ruler longer mark color
        fontColor: '#DEDEDE', // ruler font color
        shadowColor: '#525252', // ruler shadow color
        lineColor: '#51d6a9',
        borderColor: '#B5B5B5',
      }
    : {
        bgColor: 'transparent',
        lineColor: '#51d6a9',
        lineType: 'dashed',
        shadowColor: '#e9f7fe', // ruler shadow color
      };
});
```

**Comment by kakajun** [comment]
跟版本没啥关系哈, 只要用的时候把那个动态计算提上去  
![image](https://github.com/user-attachments/assets/18478b3d-3e26-4902-a1bb-a271226ef198)

**Comment by xiaojunjie-chn** [comment]
> 跟版本没啥关系哈, 只要用的时候把那个动态计算提上去 ![image](https://private-user-images.githubusercontent.com/38216933/368959515-18478b3d-3e26-4902-a1bb-a271226ef198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4ODkyMTYsIm5iZiI6MTcyNjg4ODkxNiwicGF0aCI6Ii8zODIxNjkzMy8zNjg5NTk1MTUtMTg0NzhiM2QtM2UyNi00OTAyLWExYmItYTI3MTIyNmVmMTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDAzMjE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGNjMDhlNmIzM2NlNmYwMTA3NTNmNThkYTRhM2ZjYzE5YmQ2MGM4ZTRiMjA0NGQ1ZmU2ZmRlMDFlMDc2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5Ve3t5KF9qFx8DYgtZR-VkWlCJP2WHmkKQX2oDfbPC8)

感谢大佬回复。这个计算属性我是提上来的，尝试过也是不行。标尺的阴影颜色还是不跟随变化
```vue
<SketchRule
            v-if="sketchRuleReDraw"
            ref="sketchruleRef"
            :key="rendIndex"
            :scale="scale"
            :width="canvasBox.width"
            :height="canvasBox.height"
            v-bind="post"
            :palette="rulerPalette"
            :panzoom-option="panzoomOption"
            style="height: calc(100% - 40px)"
          >
```
