### ISSUE TITLE
npm run build:demo2报错

### ISSUE THREAD

**Issue by guolixin1121** [kakajun/vue3-sketch-ruler#8]
'default' is not exported by ../../node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by ../../node_modules/vue-demi/lib/index.mjs

**Comment by kakajun** [comment]
哈哈, 刚刚正在升级插件, 现在已经好了, 再拉一下, 重新装插件

**Comment by guolixin1121** [comment]
重新下载了源码，运行build:demo2报错
[vite]: Rollup failed to resolve import "@vue/composition-api/dist/vue-composition-api.mjs" from "../../node_modules/vue-demi/lib/index.mjs".
根目录下手动安装了@vue/composition-api/，又报错
error during build:
Error: 'default' is not exported by ../../node_modules/vue/dist/vue.runtime.esm-bundler.js, imported by ../../node_modules/vue-demi/lib/index.mjs

是不是少了什么步骤，感觉是vude-demi里vue没有加载进来
