### ISSUE TITLE
isShowReferLine 自定义的 处理 辅助线的隐藏显示，没有效果

### ISSUE THREAD

**Issue by frontend-qin** [kakajun/vue3-sketch-ruler#9]

**Comment by frontend-qin** [comment]
`  <SketchRule
      :thick="state.thick"
      :scale="state.scale"
      :width="ruleWith"
      :height="ruleHeight"
      :start-x="state.startX"
      :start-y="state.startY"
      :shadow="state.shadow"
      :isShowReferLine="state.isShowReferLine"
      :corner-active="true"
      :lines="state.lines"
      :palette="palette"
    >`
通过事件自己 控制  state.isShowReferLine 的值为true | false, 辅助线不会隐藏显示， 是不是源码需要 watch 一下

**Comment by kakajun** [comment]
已经watch了
